apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  selector:
    matchLabels: { app: streaming }
  template:
    metadata:
      labels: { app: streaming }
    spec:
      containers:
        - name: streaming
          image: 994114819227.dkr.ecr.us-east-1.amazonaws.com/streaming-stream:1.0.13
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef: { name: streamingapp-config }
            - secretRef: { name: streamingapp-secret }
          env:
            - name: PORT
              value: "3002"
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 500m, memory: 512Mi }
          readinessProbe:
            tcpSocket: { port: 3002 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 3002 }
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-svc
spec:
  type: ClusterIP
  selector: { app: streaming }
  ports:
    - port: 3002
      targetPort: 3002
